### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [shrtlist/SLTDoubleTapSegmentedControl#1]
Hi, thanks for the control. Can you please add it to Cocoapods?

**Comment by shrtlist** [comment]
Thanks Isuru. Would you be able to do this as a pull request?

**Comment by Isuru-Nanayakkara** [comment]
Hi! Although I visit Github a lot, I have very little knowledge in using it. I don't know how to create a pull request and integrate it with Cocoapods. Sorry.

**Comment by shrtlist** [comment]
Closing due to addition of Cocoapods support, @Isuru-Nanayakkara .
